### ISSUE TITLE
Wide table is not (obviously) scrollable

### ISSUE THREAD

**Issue by cmutel** [lilliputten/svelte-randonneur-app#28]
With a normal laptop screen, the spacing of the labels and maybe the config is such that I can't see all the columns, and can't figure out how to scroll the table over (normal HTML tables would follow common scrolling patterns).

![Screenshot 2024-01-17 at 10 37 51](https://github.com/lilliputten/svelte-randonneur-app/assets/645217/1cabdd65-34cf-4c6b-b05d-320af492ab36)

**Comment by lilliputten** [comment]
Has fixed in PR #33.
