### ISSUE TITLE
Filtering string interface UX

### ISSUE THREAD

**Issue by cmutel** [lilliputten/svelte-randonneur-app#66]
Filtering using string queries is awesome and fast. Getting real-time feedback on what you are typing is quite nice, but the model popup and darkening of the content makes it much harder than it should be to see that real-time feedback. Please either reduce or even remove the darkening effect so that we can see what happens when we search.

**Comment by cmutel** [comment]
@lilliputten

**Comment by lilliputten** [comment]
Do we really need this real-time behaviour (it just was simpler to faster to implement it this way)?

I can use the model like used on row edit popup: when changes applying only after pressing the 'Ok' button. Would it be better?

**Comment by cmutel** [comment]
> Do we really need this real-time behaviour (it just was simpler to faster to implement it this way)?

Yes! It really make a difference, especially with unfamiliar data.

**Comment by lilliputten** [comment]
@cmutel Got you. Going to make the background more transparent. But I think if this thing is so important, then it'd be better to try to implement filters more like it was before: in a non-blocking way when it hasn't obscured the table and blocked its controls?

**Comment by cmutel** [comment]
Sure, that's also a possibility. But I think a clear view of the list when filtering would be fine for now.

**Comment by lilliputten** [comment]
Fixed in PRs #76, #77.

v.0.0.15

![20240130-232348](https://github.com/lilliputten/svelte-randonneur-app/assets/6855837/bb825c7d-6808-4a76-aa50-2016339ce147)
