### ISSUE TITLE
Categorical filters UX improvements

### ISSUE THREAD

**Issue by cmutel** [lilliputten/svelte-randonneur-app#67]
@lilliputten e.g. for units they show units not available in the raw data. This is confusing for users. I also think it would be nice to show the number of elements that meet each categorical selection filter, like `kg (142)`.

**Comment by lilliputten** [comment]
I don't understand: do I have a bug which shows absent units?

Not sure about numbers: I need check if it's possible and can be implemented in an optimal way.

**Comment by cmutel** [comment]
OK, you are right - you show the units available, though you can get zero results with the combination of other filters. Closing.
