### ISSUE TITLE
Conversion factor data type

### ISSUE THREAD

**Issue by cmutel** [lilliputten/svelte-randonneur-app#68]
@lilliputten This should always be a float, not an integer. Most often it will be something like 0.001.

**Comment by lilliputten** [comment]
If I'm right the app doesn't make differences between floats and integers: there aren't any checks and conversions for this.

**Comment by cmutel** [comment]
OK, then maybe let's remove the arrows, as they increment integers, which is never going to be correct for this app.

**Comment by lilliputten** [comment]
> OK, then maybe let's remove the arrows, as they increment integers, which is never going to be correct for this app.

Ah! I've got you: you talked about *crement arrows. They appear due to 'input type=number' type. I can just turn it back to the raw string.

**Comment by lilliputten** [comment]
Fixed in PRs #76, #77.

v.0.0.15
