### ISSUE TITLE
Installation instuctions

### ISSUE THREAD

**Issue by cmutel** [lilliputten/svelte-randonneur-app#69]
@lilliputten These need to be more explicit - not everyone uses NPM every day, or even every year. We don't need a whole novel here, but a little bit more would help a lot.

**Comment by lilliputten** [comment]
It cames from original svelte technical readme. I'm going to extend it with project-specific instructions (for the bdwv/uild cycle).Probably, we need the end-user help too, like it was in sankey app.

**Comment by cmutel** [comment]
Not sure about the online help, as it is pretty self-explanatory; but let's see. I need help with the install though :)

**Comment by lilliputten** [comment]
@cmutel  Can you explain what kind of install help do you need?

There is only one way to install (from sources, to build): using `npm install` (or using yarn) and it's almost described there. (I'll try to re-check it and add missing details.)

There is the second way: to get a built bundle (to host it on a web server), but isn't it a little different task?

**Comment by lilliputten** [comment]
@cmutel

Added some readme instructions in PRs #73 and #74.

Check it at https://github.com/lilliputten/svelte-randonneur-app pls.

v.0.0.13.
