### ISSUE TITLE
Pages and records should update following the filters applied

### ISSUE THREAD

**Issue by cmutel** [lilliputten/svelte-randonneur-app#70]
This text: `Displayed page 1 out of 0 (total pages: 331, records: 3304)`

The number of pages updates but the other values don't. This is confusing for me, and certainly worse for normal users. Instead, we need something which gives a better sense of how many records are present given the current filters, and another part which shows the total number. The user wants to see both.

**Comment by lilliputten** [comment]
@cmutel

I don't understand it:

I see that the records count (and pages) number is updating if data has been added. And number of available pages is updated along with changing filters.

What exactly should I fix here?

I've added some checks to prevent displaying zeros here (will appear in the next v.0.0.14).

**Comment by cmutel** [comment]
The text currently displays the following:

- Number of pages in the filtered result set
- Number of records and number of pages in total

I would like to see:

- Number of records and number of pages in the filtered result set
- Number of records and number of pages in total

😄

**Comment by lilliputten** [comment]
@cmutel

Now are displayed:

- Current page number.
- Available (filtered) pages count.
- Total pages count (if not equal filtered pages).
- Total records count.

So, according to the current state (above) and your requirements, I have to add the available (filtered) records count, right?

**Comment by cmutel** [comment]
Yes, and if not records show something sensible instead of `page 1 of 0` 😸

**Comment by lilliputten** [comment]
@cmutel It's going to work this way:

![20240130-215806](https://github.com/lilliputten/svelte-randonneur-app/assets/6855837/191bb93d-bf21-41f7-b3d5-c61049e8110b)

![20240130-215857](https://github.com/lilliputten/svelte-randonneur-app/assets/6855837/906aeb58-0591-4cb8-b575-38c880532a44)

(Finishing it right now.)

**Comment by lilliputten** [comment]
Fixed in PR #75.

v.0.0.14.
