### ISSUE TITLE
Categorical filters seem to do text matching

### ISSUE THREAD

**Issue by cmutel** [lilliputten/svelte-randonneur-app#71]
Start with loading the agribalyse demo data. Filter source units by "g". This still shows all "kg" rows. Instead of doing subtext matching, the logic should do equality comparisons.

**Comment by lilliputten** [comment]
That's true: it has been made for a 'list of lists' type (like 'categories'), but I forgot to make it for those specific data columns (of 'select' type): 'unit', 'categories', 'role'.

Fixed in PR #72, v.0.0.13.
